// scripts/generate-mimes.ts

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import DB from "mime-db";

const OUTPUT = resolve("src/generated/mime.ts");

const SOURCES = {
	iana: 4,
	apache: 2,
	nginx: 1,
};

const IGNORE = /\/(?:x-|vnd\.)/;

const raw = Object.create(null);

function compare(previous, next) {
	const p = SOURCES[DB[previous].source] ?? 3;

	const n = SOURCES[DB[next].source] ?? 3;

	if (p !== n) {
		return n > p ? next : previous;
	}

	// Prefer shorter official mime
	return previous.length <= next.length ? previous : next;
}

export function generateMimes() {
	for (const mime in DB) {
		if (IGNORE.test(mime)) continue;

		const extensions = DB[mime].extensions;
		if (!extensions) continue;

		for (let i = 0; i < extensions.length; i++) {
			const extension = extensions[i];
			const previous = raw[extension];

			raw[extension] = previous ? compare(previous, mime) : mime;
		}
	}

	const extensions = Object.keys(raw).sort();

	const key = (extension) =>
		/^[$A-Za-z_$][$\w]*$/.test(extension)
			? extension
			: JSON.stringify(extension);

	let source = `\
/**
 * This file is automatically generated.
 * Do not edit manually.
 */

export const mimes = {
	__proto__: null,\n`;

	for (let i = 0; i < extensions.length; i++) {
		const extension = extensions[i];
		source += `\t${key(extension)}: ${JSON.stringify(raw[extension])},\n`;
	}

	source += `} as const;

export type MimeExtension = Exclude<keyof typeof mimes, "__proto__">;

export type MimeType = (typeof mimes)[MimeExtension];

/**
 * Returns the MIME type associated with an extension.
 */
export const lookup = (extension: string): string | undefined =>
	(mimes as unknown as Record<string, string>)[extension.toLowerCase()];
 `;

	mkdirSync(dirname(OUTPUT), { recursive: true });

	writeFileSync(OUTPUT, source);

	console.log(`✓ Generated ${extensions.length} mime types`);
}
